name: Deploy to Firebase Hosting via Workload Identity

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    permissions:
      contents: 'read'    # Allow GitHub Actions to access the code
      id-token: 'write'   # Required for Workload Identity Federation

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/740738140064/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
          service_account: "github-action-904345802@homevu-c0f93.iam.gserviceaccount.com"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: firebase deploy --project homevu-c0f93
